#!/bin/bash
# Post installation script

set -o nounset # do not accept unset variables

TEXTDOMAIN=bl-welcome

BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
BL_WELCOME_LIBDIR='/usr/lib/bunsen/welcome'

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

sourcePage() {
    if [[ ! -r "$BL_WELCOME_LIBDIR/$1" ]]; then
        echo $"Error: Unable to read $1 in $BL_WELCOME_LIBDIR" >&2
        exit 1
    fi
    . "$BL_WELCOME_LIBDIR/$1"
}

# default url for added Debian backports etc.
default_mirror='http://deb.debian.org/debian'

# matches most mirrors
# add (?=.*debian) at beginning to insist on 'debian' somewhere (needs PCRE)
mirror_regex='http://([[:alnum:]_-]+\.)+[[:alnum:]]+(/[[:alnum:]._-]+)*/?'

log_dir="$HOME/.cache/bunsen-welcome"
mkdir -p "$log_dir"
logfile="$log_dir"/bl-welcome.log

log() {
    echo "
${1-}
" >> "$logfile"
}

warnlog() {
    echo "######## WARNING ########
${1-}
------------------------------------------------" >> "$logfile"
}

STEPS_BASIC=('apt-update' 'apt-upgrade' 'system-tweaks' 'install-images-extra' 'install-java-packages' 'add-debian-backports' 'add-bunsen-backports' 'install-flashplugin' 'devel')
STEPS_DEVEL=('devel-install-version-control-tools' 'devel-install-lamp-stack' 'devel-install-packaging-tools')

# prints something like: -------[ page 1 of 10 ]-------
header() {
    local width=$(tput cols 2>/dev/tty)
    local headerLength=$((width - 8)) # 8 is for '[  ]' and 2 spaces margins
    local headerText=$(printf $"page %d of %d" "$STEP" "$STEPS")
    local dashesStart=$( printf "%$(( (headerLength - ${#headerText}) / 2 ))s" )
    local dashesEnd=$( printf "%$(( (headerLength - ${#headerText}) / 2 + (headerLength - ${#headerText}) % 2 ))s" )
    echo "  ${dashesStart// /-}[ ${headerText} ]${dashesEnd// /-}"$'\n'
}

# Usage: setupPage title text [prompt [prompt-extra-arg]]
# Omit prompt for noninteractive page.
setupPage() {
    sleep 1
    tput clear
    header
    say "${1^^}
${1//?/-}

$2
"
    [[ ${3-} ]] || { sleep 1;return 0;}
    prompt "  $3" "${4:-}"
    return $?
}

# Common function for most install scripts. USE THIS unless you really can't.
# Usage: installPage title text package...
# example: installPage 'LibreOffice suite' 'This will install libreoffice' 'libreoffice'
# Returns 0 if installation suceeds, 2 if package(s) already installed
# or install declined, 1 if there was an error.
installPage() {
    local title=$"install"" $1"
    local text="$1 has already been installed."
    allInstalled "${@:3}" && {
        setupPage "$title" "$text"
        return 2
    }
    text="$2"$'\n\n'$"If you choose to do this, the following packages will be installed:""

    ${*:3}

"$"Note: additional packages listed as dependencies will also be installed."

    local prompt=$"Would you like to install"" ${1}?"

    if setupPage "$title" "$text" "$prompt" 'N'
    then
        if safeInstall "${@:3}"
        then
            return 0
        else
            say '...going to next page.' 1
        fi
    else
        return 2
    fi
    return 1
}

[[ -d /lib/live ]] && exit 0

if [[ ${1-} = '--firstrun' ]]; then # First run, from autostart
    [[ -e $HOME/.config/bunsen/bl-welcome ]] && exit 0
fi

terminalCheck -T 'WELCOME!'

exec > >( tee -a "$logfile" ) 2>&1

log "Starting bl-welcome for $USER at $(date)"

createFlag 'bl-welcome'

if [[ $( id -u ) -eq 0 ]]; then
    echo $"Error: This script should not be run directly by root." >&2
    exit 1
fi

# Run through steps
STEP=1
if [[ -e $HOME/.config/bunsen/bl-welcome-understood ]]; then
    (( STEPS = ${#STEPS_BASIC[@]} + ${#STEPS_DEVEL[@]} + 2 )) # 2 is intro and fini
    sourcePage intro
else
    (( STEPS = ${#STEPS_BASIC[@]} + ${#STEPS_DEVEL[@]} + 3 )) # 3 is intro, warning and fini
    sourcePage intro
    ((STEP++))
    sourcePage warning
    createFlag 'bl-welcome-understood'
fi
sleep 2
tput clear
connectiontest

DEVEL=false

for curStep in "${STEPS_BASIC[@]}"; do
    ((STEP++))
    sourcePage "$curStep"
done

if $DEVEL; then
    for curStep in "${STEPS_DEVEL[@]}"; do
        ((STEP++))
        sourcePage "$curStep"
    done
fi
STEP=$STEPS
sourcePage fini

exit 0
